/*
 * PROJECT: GEMMapper
 * FILE: matches_classify_logit_models.c
 * DATE: 06/06/2012
 * AUTHOR(S): Santiago Marco-Sola <santiagomsola@gmail.com>
 * DESCRIPTION: TODO
 */

#include "matches/matches_classify_logit_models.h"

/*
 * SE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_single_end_default = {
  .unique_logit_coeff = {
      .coeff_intercept                       = -288.7790,
      .coeff_first_map_edit_distance_norm    = 28.9158,
      .coeff_first_map_event_distance_norm   = 249.5996,
      .coeff_first_map_swg_score_norm        = 7.5823,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_mcs_end1                        = 5.3135,
      .coeff_mcs_end2                        = 0.0,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = -0.2323,
      .coeff_mappability_p                   = 0.4030,
      .coeff_mappability_2p                  = 0.0,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                       = -293.0609,
      .coeff_first_map_edit_distance_norm    = 21.3134,
      .coeff_first_map_event_distance_norm   = 260.9199,
      .coeff_first_map_swg_score_norm        = 13.6089,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = -5.1878,
      .coeff_mcs_end1                        = 4.8626,
      .coeff_mcs_end2                        = 0.0,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = -0.3664,
      .coeff_mappability_p                   = 0.3714,
      .coeff_mappability_2p                  = 0.0,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
  },
  .ties_logit_coeff = {
      .coeff_intercept                       = -157.2407,
      .coeff_first_map_edit_distance_norm    = 72.3942,
      .coeff_first_map_event_distance_norm   = 136.6183,
      .coeff_first_map_swg_score_norm        = 0.0,
      .coeff_subdominant_edit_distance_norm  = -52.6755,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_mcs_end1                        = 1.6797,
      .coeff_mcs_end2                        = 0.0,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = 0.0,
      .coeff_mappability_p                   = 0.2444,
      .coeff_mappability_2p                  = 0.0,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
  },
};
/*
 * PE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_paired_end_default = {
  .unique_logit_coeff = {
      .coeff_intercept                       = -279.7110,
      .coeff_first_map_edit_distance_norm    = 83.0661,
      .coeff_first_map_event_distance_norm   = 197.1645,
      .coeff_first_map_swg_score_norm        = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_mcs_end1                        = 2.2675,
      .coeff_mcs_end2                        = 1.6833,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = 0.0,
      .coeff_mappability_p                   = 0.0,
      .coeff_mappability_2p                  = 0.0,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 1.1772,
      .coeff_mapq_end2                       = 0.8718,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                       = 0.0,
      .coeff_first_map_edit_distance_norm    = 0.0,
      .coeff_first_map_event_distance_norm   = 0.0,
      .coeff_first_map_swg_score_norm        = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_mcs_end1                        = 0.0,
      .coeff_mcs_end2                        = 0.0,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = 0.0,
      .coeff_mappability_p                   = 0.0,
      .coeff_mappability_2p                  = 0.0,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
  },
  .ties_logit_coeff = {
      .coeff_intercept                       = -192.37068,
      .coeff_first_map_edit_distance_norm    = 26.44741,
      .coeff_first_map_event_distance_norm   = 159.49776,
      .coeff_first_map_swg_score_norm        = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_mcs_end1                        = 1.18447,
      .coeff_mcs_end2                        = 1.35970,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = 0.63607,
      .coeff_mappability_p                   = 0.0,
      .coeff_mappability_2p                  = 0.83980,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 0.07158,
      .coeff_mapq_end2                       = 0.06600,
  },
};

/*

.coeff_intercept                       = 0.0,
.coeff_first_map_edit_distance_norm    = 0.0,
.coeff_first_map_event_distance_norm   = 0.0,
.coeff_first_map_swg_score_norm        = 0.0,
.coeff_subdominant_edit_distance_norm  = 0.0,
.coeff_subdominant_event_distance_norm = 0.0,
.coeff_subdominant_swg_score_norm      = 0.0,
.coeff_mcs_end1                        = 0.0,
.coeff_mcs_end2                        = 0.0,
.coeff_first_stratum_matches           = 0.0,
.coeff_accepted_candidates_end1        = 0.0,
.coeff_accepted_candidates_end2        = 0.0,
.coeff_max_region_length_norm          = 0.0,
.coeff_mappability_p                   = 0.0,
.coeff_mappability_2p                  = 0.0,
.coeff_first_map_template_size_sigma   = 0.0,
.coeff_subdominant_template_size_sigma = 0.0,
.coeff_mapq_end1                       = 0.0,
.coeff_mapq_end2                       = 0.0,

 */
