/*
 * PROJECT: GEMMapper
 * FILE: matches_classify_logit_models.c
 * DATE: 06/06/2012
 * AUTHOR(S): Santiago Marco-Sola <santiagomsola@gmail.com>
 * DESCRIPTION: TODO
 */

#include "matches/matches_classify_logit_models.h"

/*
 * SE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_single_end_default = {
  .unique_logit_coeff = {
      .coeff_intercept                       = -251.5606,
      .coeff_first_map_edit_distance_norm    = 25.3611,
      .coeff_first_map_event_distance_norm   = 208.2101,
      .coeff_first_map_swg_score_norm        = 11.8274,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_mcs_end1                        = 5.1056,
      .coeff_mcs_end2                        = 0.0,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = 0.0,
      .coeff_kmer_frequency                  = 0.7912,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                       = -370.6443,
      .coeff_first_map_edit_distance_norm    = 66.5471,
      .coeff_first_map_event_distance_norm   = 273.6853,
      .coeff_first_map_swg_score_norm        = 0.0,
      .coeff_subdominant_edit_distance_norm  = -53.2541,
      .coeff_subdominant_event_distance_norm = 79.9806,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_mcs_end1                        = 4.8223,
      .coeff_mcs_end2                        = 0.0,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = -0.5543,
      .coeff_kmer_frequency                  = 0.8111,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
  },
  .ties_logit_coeff = {
      .coeff_intercept                       = -147.211,
      .coeff_first_map_edit_distance_norm    = 71.027,
      .coeff_first_map_event_distance_norm   = 135.447,
      .coeff_first_map_swg_score_norm        = 19.747,
      .coeff_subdominant_edit_distance_norm  = -62.066,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = -17.575,
      .coeff_mcs_end1                        = 1.453,
      .coeff_mcs_end2                        = 0.0,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = 0.0,
      .coeff_kmer_frequency                  = 0.0,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
  },
};
/*
 * PE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_paired_end_default = {
  .unique_logit_coeff = {
      .coeff_intercept                       = -279.7110,
      .coeff_first_map_edit_distance_norm    = 83.0661,
      .coeff_first_map_event_distance_norm   = 197.1645,
      .coeff_first_map_swg_score_norm        = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_mcs_end1                        = 2.2675,
      .coeff_mcs_end2                        = 1.6833,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = 0.0,
      .coeff_kmer_frequency                  = 0.0,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 1.1772,
      .coeff_mapq_end2                       = 0.8718,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                       = 0.0,
      .coeff_first_map_edit_distance_norm    = 0.0,
      .coeff_first_map_event_distance_norm   = 0.0,
      .coeff_first_map_swg_score_norm        = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_mcs_end1                        = 0.0,
      .coeff_mcs_end2                        = 0.0,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = 0.0,
      .coeff_kmer_frequency                  = 0.0,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
  },
  .ties_logit_coeff = {
      .coeff_intercept                       = -192.37068,
      .coeff_first_map_edit_distance_norm    = 26.44741,
      .coeff_first_map_event_distance_norm   = 159.49776,
      .coeff_first_map_swg_score_norm        = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_mcs_end1                        = 1.18447,
      .coeff_mcs_end2                        = 1.35970,
      .coeff_first_stratum_matches           = 0.0,
      .coeff_accepted_candidates_end1        = 0.0,
      .coeff_accepted_candidates_end2        = 0.0,
      .coeff_max_region_length_norm          = 0.63607,
      .coeff_kmer_frequency                  = 0.0,
      .coeff_first_map_template_size_sigma   = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_mapq_end1                       = 0.07158,
      .coeff_mapq_end2                       = 0.06600,
  },
};

/*

.coeff_intercept                       = 0.0,
.coeff_first_map_edit_distance_norm    = 0.0,
.coeff_first_map_event_distance_norm   = 0.0,
.coeff_first_map_swg_score_norm        = 0.0,
.coeff_subdominant_edit_distance_norm  = 0.0,
.coeff_subdominant_event_distance_norm = 0.0,
.coeff_subdominant_swg_score_norm      = 0.0,
.coeff_mcs_end1                        = 0.0,
.coeff_mcs_end2                        = 0.0,
.coeff_first_stratum_matches           = 0.0,
.coeff_accepted_candidates_end1        = 0.0,
.coeff_accepted_candidates_end2        = 0.0,
.coeff_max_region_length_norm          = 0.0,
.coeff_kmer_frequency                  = 0.0,
.coeff_first_map_template_size_sigma   = 0.0,
.coeff_subdominant_template_size_sigma = 0.0,
.coeff_mapq_end1                       = 0.0,
.coeff_mapq_end2                       = 0.0,

 */
