/*
 * PROJECT: GEMMapper
 * FILE: matches_classify_logit_models.c
 * DATE: 06/06/2012
 * AUTHOR(S): Santiago Marco-Sola <santiagomsola@gmail.com>
 * DESCRIPTION: TODO
 */

#include "matches/matches_classify_logit_models.h"

/*
 * SE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_single_end_default = {
  .unique_logit_coeff = {
      .coeff_intercept                       = -273.7720,
      .coeff_map_edit_distance_norm          = 87.7310,
      .coeff_map_event_distance_norm         = 190.6858,
      .coeff_map_swg_score_norm              = 0.0,
      .coeff_map_template_size_sigma         = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
      .coeff_best_map_edit_distance_norm     = 0.0,
      .coeff_best_map_event_distance_norm    = 0.0,
      .coeff_best_map_swg_score_norm         = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_best_map_template_size_sigma    = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_matches_accepted                = 0.0,
      .coeff_mcs_end1                        = 3.1012,
      .coeff_mcs_end2                        = 0.0,
      .coeff_max_region_length_norm          = -1.3930,
      .coeff_kmer_frequency                  = 0.5103,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                       = -183.6897,
      .coeff_map_edit_distance_norm          = 112.9459,
      .coeff_map_event_distance_norm         = 245.1781,
      .coeff_map_swg_score_norm              = 0.0,
      .coeff_map_template_size_sigma         = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
      .coeff_best_map_edit_distance_norm     = 0.0,
      .coeff_best_map_event_distance_norm    = 0.0,
      .coeff_best_map_swg_score_norm         = 39.8445,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = -162.3271,
      .coeff_subdominant_swg_score_norm      = -55.3463,
      .coeff_best_map_template_size_sigma    = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_matches_accepted                = 0.0,
      .coeff_mcs_end1                        = 1.1506,
      .coeff_mcs_end2                        = 0.0,
      .coeff_max_region_length_norm          = -0.2712,
      .coeff_kmer_frequency                  = 0.0,
  },
  .ties_logit_coeff = {
      .coeff_intercept                       = -51.0044,
      .coeff_map_edit_distance_norm          = 65.0587,
      .coeff_map_event_distance_norm         = 252.3963,
      .coeff_map_swg_score_norm              = 0.0,
      .coeff_map_template_size_sigma         = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
      .coeff_best_map_edit_distance_norm     = 0.0,
      .coeff_best_map_event_distance_norm    = 0.0,
      .coeff_best_map_swg_score_norm         = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = -264.0290,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_best_map_template_size_sigma    = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_matches_accepted                = 0.0,
      .coeff_mcs_end1                        = 0.4445,
      .coeff_mcs_end2                        = 0.0,
      .coeff_max_region_length_norm          = -0.5069,
      .coeff_kmer_frequency                  = 0.0,
  },
};
/*
 * PE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_paired_end_default = {
  .unique_logit_coeff = {
      .coeff_intercept                       = -355.519,
      .coeff_map_edit_distance_norm          = 113.282,
      .coeff_map_event_distance_norm         = 236.628,
      .coeff_map_swg_score_norm              = 0.0,
      .coeff_map_template_size_sigma         = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
      .coeff_best_map_edit_distance_norm     = 0.0,
      .coeff_best_map_event_distance_norm    = 0.0,
      .coeff_best_map_swg_score_norm         = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_best_map_template_size_sigma    = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_matches_accepted                = 0.0,
      .coeff_mcs_end1                        = 1.947,
      .coeff_mcs_end2                        = 1.881,
      .coeff_max_region_length_norm          = 0.0,
      .coeff_kmer_frequency                  = 1.625,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                       = -630.1680,
      .coeff_map_edit_distance_norm          = 0.0,
      .coeff_map_event_distance_norm         = 639.0854,
      .coeff_map_swg_score_norm              = 0.0,
      .coeff_map_template_size_sigma         = 0.0,
      .coeff_mapq_end1                       = 0.0,
      .coeff_mapq_end2                       = 0.0,
      .coeff_best_map_edit_distance_norm     = 0.0,
      .coeff_best_map_event_distance_norm    = 0.0,
      .coeff_best_map_swg_score_norm         = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = -14.6836,
      .coeff_best_map_template_size_sigma    = 0.0,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_matches_accepted                = 0.0,
      .coeff_mcs_end1                        = 3.4951,
      .coeff_mcs_end2                        = 3.5949,
      .coeff_max_region_length_norm          = 0.4758,
      .coeff_kmer_frequency                  = 0.0,
  },
  .ties_logit_coeff = {
      .coeff_intercept                       = -295.27121,
      .coeff_map_edit_distance_norm          = 37.43897,
      .coeff_map_event_distance_norm         = 277.49174,
      .coeff_map_swg_score_norm              = -23.19804,
      .coeff_map_template_size_sigma         = -1.91904,
      .coeff_mapq_end1                       = 0.03587,
      .coeff_mapq_end2                       = 0.05515,
      .coeff_best_map_edit_distance_norm     = 0.0,
      .coeff_best_map_event_distance_norm    = 0.0,
      .coeff_best_map_swg_score_norm         = 0.0,
      .coeff_subdominant_edit_distance_norm  = 0.0,
      .coeff_subdominant_event_distance_norm = 0.0,
      .coeff_subdominant_swg_score_norm      = 0.0,
      .coeff_best_map_template_size_sigma    = 1.74484,
      .coeff_subdominant_template_size_sigma = 0.0,
      .coeff_matches_accepted                = 0.0,
      .coeff_mcs_end1                        = 0.99907,
      .coeff_mcs_end2                        = 1.04749,
      .coeff_max_region_length_norm          = 0.57338,
      .coeff_kmer_frequency                  = 0.0,
  },
};

/*

.coeff_intercept                       = 0.0,
.coeff_map_edit_distance_norm          = 0.0,
.coeff_map_event_distance_norm         = 0.0,
.coeff_map_swg_score_norm              = 0.0,
.coeff_map_template_size_sigma         = 0.0,
.coeff_mapq_end1                       = 0.0,
.coeff_mapq_end2                       = 0.0,
.coeff_best_map_edit_distance_norm     = 0.0,
.coeff_best_map_event_distance_norm    = 0.0,
.coeff_best_map_swg_score_norm         = 0.0,
.coeff_subdominant_edit_distance_norm  = 0.0,
.coeff_subdominant_event_distance_norm = 0.0,
.coeff_subdominant_swg_score_norm      = 0.0,
.coeff_best_map_template_size_sigma    = 0.0,
.coeff_subdominant_template_size_sigma = 0.0,
.coeff_matches_accepted                = 0.0,
.coeff_mcs_end1                        = 0.0,
.coeff_mcs_end2                        = 0.0,
.coeff_max_region_length_norm          = 0.0,
.coeff_kmer_frequency                  = 0.0,

 */
