/*
 *  GEM-Mapper v3 (GEM3)
 *  Copyright (c) 2011-2017 by Santiago Marco-Sola  <santiagomsola@gmail.com>
 *
 *  This file is part of GEM-Mapper v3 (GEM3).
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * PROJECT: GEM-Mapper v3 (GEM3)
 * AUTHOR(S): Santiago Marco-Sola <santiagomsola@gmail.com>
 */

#include "matches/classify/matches_classify_logit_models.h"

/*
 * SE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_single_end_fast = {
  .unique_logit_coeff = {
      .coeff_intercept                            = -181.02931,
      .coeff_primary_edit_distance_norm           = 28.79873,
      .coeff_primary_event_distance_norm          = 128.23030,
      .coeff_primary_swg_score_norm               = 12.07916,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 4.41750,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 5.32615,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.56017,
      .coeff_max_region_length_norm               = -1.03703,
      .coeff_kmer_frequency                       = 1.27794,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                            = -217.96172,
      .coeff_primary_edit_distance_norm           = 29.47740,
      .coeff_primary_event_distance_norm          = 198.41906,
      .coeff_primary_swg_score_norm               = 9.33518,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = -5.78130,
      .coeff_subdominant_event_distance_norm      = -8.74653,
      .coeff_subdominant_swg_score_norm           = -11.08246,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 1.40886,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 3.38050,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.69496,
      .coeff_max_region_length_norm               = -0.23906,
      .coeff_kmer_frequency                       = 0.29553,
  },
  .mmaps_d1_logit_coeff = {
      .coeff_intercept                            = -155.64125,
      .coeff_primary_edit_distance_norm           = 14.97801,
      .coeff_primary_event_distance_norm          = 135.84997,
      .coeff_primary_swg_score_norm               = 11.95730,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = -9.62717,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 0.55422,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 2.18349,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.18208,
      .coeff_max_region_length_norm               = 0.28453,
      .coeff_kmer_frequency                       = 0.0,
  },
};
const matches_classify_logit_model_t logit_model_single_end_sensitive = {
  .unique_logit_coeff = {
      .coeff_intercept                            = -296.0323,
      .coeff_primary_edit_distance_norm           = 80.4342,
      .coeff_primary_event_distance_norm          = 195.6086,
      .coeff_primary_swg_score_norm               = 11.0877,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 2.4785,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 5.8130,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = -0.9217,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 0.7033,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                            = -199.63966,
      .coeff_primary_edit_distance_norm           = 45.88615,
      .coeff_primary_event_distance_norm          = 220.15450,
      .coeff_primary_swg_score_norm               = 21.40784,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 23.36730,
      .coeff_subdominant_event_distance_norm      = -85.79431,
      .coeff_subdominant_swg_score_norm           = -22.97365,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = -1.17052,
      .coeff_aligned_candidates                   = 1.41135,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 1.35653,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = -1.49656,
      .coeff_max_region_length_norm               = 0.82873,
      .coeff_kmer_frequency                       = 0.0,
  },
  .mmaps_d1_logit_coeff = {
      .coeff_intercept                            = -40.70489,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 125.76666,
      .coeff_primary_swg_score_norm               = 18.32745,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = -104.23335,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = -0.52461,
      .coeff_aligned_candidates                   = 0.27520,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 1.42575,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = -0.61043,
      .coeff_max_region_length_norm               = 0.74663,
      .coeff_kmer_frequency                       = 0.17762,
  },
};
/*
 * PE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_paired_end_fast = {
  .unique_logit_coeff = {
      .coeff_intercept                            = -384.11434,
      .coeff_primary_edit_distance_norm           = 62.70540,
      .coeff_primary_event_distance_norm          = 315.37790,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = -4.47075,
      .coeff_mapq_end1                            = 5.15099,
      .coeff_mapq_end2                            = 12.15196,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 2.58307,
      .coeff_mcs_end2                             = 2.36390,
      .coeff_avg_region_length_norm               = -0.15349,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 1.27114,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                            = -315.08686,
      .coeff_primary_edit_distance_norm           = 52.64088,
      .coeff_primary_event_distance_norm          = 351.79165,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = -9.43108,
      .coeff_mapq_end1                            = 1.69980,
      .coeff_mapq_end2                            = 2.12938,
      .coeff_subdominant_edit_distance_norm       = -28.02583,
      .coeff_subdominant_event_distance_norm      = -62.45617,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 8.83660,
      .coeff_accepted_candidates                  = 0.87282,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 1.81755,
      .coeff_mcs_end2                             = 1.85814,
      .coeff_avg_region_length_norm               = 0.0,
      .coeff_max_region_length_norm               = 0.16285,
      .coeff_kmer_frequency                       = 0.0,
  },
  .mmaps_d1_logit_coeff = {
      .coeff_intercept                            = -202.37235,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 207.78889,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.72823,
      .coeff_mapq_end2                            = 0.69805,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = -0.39385,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 0.74960,
      .coeff_mcs_end2                             = 0.78634,
      .coeff_avg_region_length_norm               = -0.08396,
      .coeff_max_region_length_norm               = 0.06907,
      .coeff_kmer_frequency                       = -0.42562,
  },
};
const matches_classify_logit_model_t logit_model_paired_end_sensitive = {
  .unique_logit_coeff = {
      .coeff_intercept                            = -336.0317,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 339.9336,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = -16.6736,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 46.3272,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 2.9354,
      .coeff_mcs_end2                             = 0.8999,
      .coeff_avg_region_length_norm               = 0.0,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 0.0,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                            = -167.66521,
      .coeff_primary_edit_distance_norm           = 59.99463,
      .coeff_primary_event_distance_norm          = 342.91292,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = -9.61716,
      .coeff_mapq_end1                            = 4.03070,
      .coeff_mapq_end2                            = 3.27252,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = -236.47815,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 4.85386,
      .coeff_accepted_candidates                  = 1.04294,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 0.66012,
      .coeff_mcs_end2                             = 0.74412,
      .coeff_avg_region_length_norm               = 0.0,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 0.0,
  },
  .mmaps_d1_logit_coeff = {
      .coeff_intercept                            = -114.05084,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 351.90767,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = -2.04953,
      .coeff_mapq_end1                            = 3.03924,
      .coeff_mapq_end2                            = 2.98679,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = -237.35984,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 1.74614,
      .coeff_accepted_candidates                  = 0.39949,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 0.47756,
      .coeff_mcs_end2                             = 0.46623,
      .coeff_avg_region_length_norm               = 0.0,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = -0.18408,
  },
};

/*

.coeff_intercept                            = 0.0,
.coeff_primary_edit_distance_norm           = 0.0,
.coeff_primary_event_distance_norm          = 0.0,
.coeff_primary_swg_score_norm               = 0.0,
.coeff_primary_template_size_sigma_norm     = 0.0,
.coeff_mapq_end1                            = 0.0,
.coeff_mapq_end2                            = 0.0,
.coeff_subdominant_edit_distance_norm       = 0.0,
.coeff_subdominant_event_distance_norm      = 0.0,
.coeff_subdominant_swg_score_norm           = 0.0,
.coeff_subdominant_template_size_sigma_norm = 0.0,
.coeff_accepted_candidates                  = 0.0,
.coeff_aligned_candidates                   = 0.0,
.coeff_accepted_matches                     = 0.0,
.coeff_mcs_end1                             = 0.0,
.coeff_mcs_end2                             = 0.0,
.coeff_avg_region_length_norm               = 0.0,
.coeff_max_region_length_norm               = 0.0,
.coeff_kmer_frequency                       = 0.0,

 */
