/*
 *  GEM-Mapper v3 (GEM3)
 *  Copyright (c) 2011-2017 by Santiago Marco-Sola  <santiagomsola@gmail.com>
 *
 *  This file is part of GEM-Mapper v3 (GEM3).
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * PROJECT: GEM-Mapper v3 (GEM3)
 * AUTHOR(S): Santiago Marco-Sola <santiagomsola@gmail.com>
 */

#include "matches/classify/matches_classify_logit_models.h"

/*
 * SE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_single_end_fast = {
  .unique_logit_coeff = {
      .coeff_intercept                            = -181.02931,
      .coeff_primary_edit_distance_norm           = 28.79873,
      .coeff_primary_event_distance_norm          = 128.23030,
      .coeff_primary_swg_score_norm               = 12.07916,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 4.41750,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 5.32615,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.56017,
      .coeff_max_region_length_norm               = -1.03703,
      .coeff_kmer_frequency                       = 1.27794,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                            = -217.96172,
      .coeff_primary_edit_distance_norm           = 29.47740,
      .coeff_primary_event_distance_norm          = 198.41906,
      .coeff_primary_swg_score_norm               = 9.33518,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = -5.78130,
      .coeff_subdominant_event_distance_norm      = -8.74653,
      .coeff_subdominant_swg_score_norm           = -11.08246,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 1.40886,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 3.38050,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.69496,
      .coeff_max_region_length_norm               = -0.23906,
      .coeff_kmer_frequency                       = 0.29553,
  },
  .mmaps_d1_logit_coeff = {
      .coeff_intercept                            = -155.64125,
      .coeff_primary_edit_distance_norm           = 14.97801,
      .coeff_primary_event_distance_norm          = 135.84997,
      .coeff_primary_swg_score_norm               = 11.95730,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = -9.62717,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 0.55422,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 2.18349,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.18208,
      .coeff_max_region_length_norm               = 0.28453,
      .coeff_kmer_frequency                       = 0.0,
  },
};
const matches_classify_logit_model_t logit_model_single_end_sensitive = {
  .unique_logit_coeff = {
      .coeff_intercept                            = -296.0323,
      .coeff_primary_edit_distance_norm           = 80.4342,
      .coeff_primary_event_distance_norm          = 195.6086,
      .coeff_primary_swg_score_norm               = 11.0877,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 2.4785,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 5.8130,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = -0.9217,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 0.7033,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                            = -199.63966,
      .coeff_primary_edit_distance_norm           = 45.88615,
      .coeff_primary_event_distance_norm          = 220.15450,
      .coeff_primary_swg_score_norm               = 21.40784,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 23.36730,
      .coeff_subdominant_event_distance_norm      = -85.79431,
      .coeff_subdominant_swg_score_norm           = -22.97365,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = -1.17052,
      .coeff_aligned_candidates                   = 1.41135,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 1.35653,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = -1.49656,
      .coeff_max_region_length_norm               = 0.82873,
      .coeff_kmer_frequency                       = 0.0,
  },
  .mmaps_d1_logit_coeff = {
      .coeff_intercept                            = -40.70489,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 125.76666,
      .coeff_primary_swg_score_norm               = 18.32745,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = -104.23335,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = -0.52461,
      .coeff_aligned_candidates                   = 0.27520,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 1.42575,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = -0.61043,
      .coeff_max_region_length_norm               = 0.74663,
      .coeff_kmer_frequency                       = 0.17762,
  },
};
/*
 * PE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_paired_end_fast = {
  .unique_logit_coeff = {
      .coeff_intercept                            = 0.0,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 0.0,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 0.0,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.0,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 0.0,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                            = 0.0,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 0.0,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 0.0,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.0,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 0.0,
  },
  .mmaps_d1_logit_coeff = {
      .coeff_intercept                            = 0.0,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 0.0,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 0.0,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.0,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 0.0,
  },
};
const matches_classify_logit_model_t logit_model_paired_end_sensitive = {
  .unique_logit_coeff = {
      .coeff_intercept                            = 0.0,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 0.0,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 0.0,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.0,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 0.0,
  },
  .mmaps_logit_coeff = {
      .coeff_intercept                            = 0.0,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 0.0,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 0.0,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.0,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 0.0,
  },
  .mmaps_d1_logit_coeff = {
      .coeff_intercept                            = 0.0,
      .coeff_primary_edit_distance_norm           = 0.0,
      .coeff_primary_event_distance_norm          = 0.0,
      .coeff_primary_swg_score_norm               = 0.0,
      .coeff_primary_template_size_sigma_norm     = 0.0,
      .coeff_mapq_end1                            = 0.0,
      .coeff_mapq_end2                            = 0.0,
      .coeff_subdominant_edit_distance_norm       = 0.0,
      .coeff_subdominant_event_distance_norm      = 0.0,
      .coeff_subdominant_swg_score_norm           = 0.0,
      .coeff_subdominant_template_size_sigma_norm = 0.0,
      .coeff_accepted_candidates                  = 0.0,
      .coeff_aligned_candidates                   = 0.0,
      .coeff_accepted_matches                     = 0.0,
      .coeff_mcs_end1                             = 0.0,
      .coeff_mcs_end2                             = 0.0,
      .coeff_avg_region_length_norm               = 0.0,
      .coeff_max_region_length_norm               = 0.0,
      .coeff_kmer_frequency                       = 0.0,
  },
};

/*

.coeff_intercept                            = 0.0,
.coeff_primary_edit_distance_norm           = 0.0,
.coeff_primary_event_distance_norm          = 0.0,
.coeff_primary_swg_score_norm               = 0.0,
.coeff_primary_template_size_sigma_norm     = 0.0,
.coeff_mapq_end1                            = 0.0,
.coeff_mapq_end2                            = 0.0,
.coeff_subdominant_edit_distance_norm       = 0.0,
.coeff_subdominant_event_distance_norm      = 0.0,
.coeff_subdominant_swg_score_norm           = 0.0,
.coeff_subdominant_template_size_sigma_norm = 0.0,
.coeff_accepted_candidates                  = 0.0,
.coeff_aligned_candidates                   = 0.0,
.coeff_accepted_matches                     = 0.0,
.coeff_mcs_end1                             = 0.0,
.coeff_mcs_end2                             = 0.0,
.coeff_avg_region_length_norm               = 0.0,
.coeff_max_region_length_norm               = 0.0,
.coeff_kmer_frequency                       = 0.0,

 */
