/*
 *  GEM-Mapper v3 (GEM3)
 *  Copyright (c) 2011-2017 by Santiago Marco-Sola  <santiagomsola@gmail.com>
 *
 *  This file is part of GEM-Mapper v3 (GEM3).
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * PROJECT: GEM-Mapper v3 (GEM3)
 * AUTHOR(S): Santiago Marco-Sola <santiagomsola@gmail.com>
 * DESCRIPTION:
 *   Approximate-String-Matching (ASM) module to verify
 *   the filtering-candidates generated by previous stages
 */

#include "filtering/candidates/filtering_candidates_buffered_bpm_align.h"
#include "filtering/candidates/filtering_candidates_buffered_bpm_distance.h"
#include "filtering/candidates/filtering_candidates_buffered_kmer_filter.h"
#include "approximate_search/approximate_search_verify_candidates.h"
#include "filtering/candidates/filtering_candidates_process.h"
#include "filtering/candidates/filtering_candidates_verify.h"
#include "filtering/candidates/filtering_candidates_extend.h"
#include "filtering/candidates/filtering_candidates_align.h"

/*
 * Debug
 */
#define DEBUG_REGION_SCHEDULE_PRINT GEM_DEEP_DEBUG

/*
 * Profile
 */
#define PROFILE_LEVEL PMED

/*
 * Verify Candidates
 */
void approximate_search_verify_candidates(
    approximate_search_t* const search,
    matches_t* const matches) {
  gem_cond_debug_block(DEBUG_SEARCH_STATE) {
    tab_fprintf(stderr,"[GEM]>ASM::Verify Candidates\n");
    tab_global_inc();
  }
  // Parameters
  pattern_t* const pattern = &search->pattern;
  filtering_candidates_t* const filtering_candidates = search->filtering_candidates;
  // Verify Candidates
  filtering_candidates_verify_candidates(filtering_candidates,pattern,matches);
  filtering_candidates_align_candidates(filtering_candidates,pattern,matches);
  search->processing_state = asearch_processing_state_candidates_verified;
  gem_cond_debug_block(DEBUG_SEARCH_STATE) { tab_global_dec(); }
}
/*
 * Verify Extend Candidate
 */
void approximate_search_verify_extend_candidate(
    filtering_candidates_t* const filtering_candidates,
    pattern_t* const candidate_pattern,
    const match_trace_t* const extended_match,
    mapper_stats_t* const mapper_stats,
    paired_matches_t* const paired_matches,
    const sequence_end_t candidate_end) {
  return filtering_candidates_extend_match(filtering_candidates,
      candidate_pattern,extended_match,paired_matches,candidate_end,mapper_stats);
}
/*
 * Kmer-filter Buffered
 */
void approximate_search_kmer_filter_buffered_copy(
    approximate_search_t* const search,
    gpu_buffer_kmer_filter_t* const gpu_buffer_kmer_filter) {
  // Add to GPU-Buffer
  filtering_candidates_buffered_kmer_filter_add(
      search->filtering_candidates,&search->filtering_candidates_buffered,
      &search->pattern,gpu_buffer_kmer_filter,&search->gpu_buffer_kmer_filter_offset);
}
void approximate_search_kmer_filter_buffered_retrieve(
    approximate_search_t* const search,
    gpu_buffer_kmer_filter_t* const gpu_buffer_kmer_filter) {
  // Retrieve from GPU-Buffer
  filtering_candidates_buffered_kmer_filter_retrieve(
      search->filtering_candidates,&search->filtering_candidates_buffered,
      &search->pattern,gpu_buffer_kmer_filter,search->gpu_buffer_kmer_filter_offset);
}
/*
 * BPM-Distance Buffered
 */
void approximate_search_bpm_distance_buffered_copy(
    approximate_search_t* const search,
    gpu_buffer_bpm_distance_t* const gpu_buffer_bpm_distance) {
  // Add to GPU-Buffer
  filtering_candidates_buffered_bpm_distance_add(
      search->filtering_candidates,&search->filtering_candidates_buffered,
      &search->pattern,gpu_buffer_bpm_distance,&search->gpu_buffer_bpm_distance_offset);
}
void approximate_search_bpm_distance_buffered_retrieve(
    approximate_search_t* const search,
    gpu_buffer_bpm_distance_t* const gpu_buffer_bpm_distance) {
  // Retrieve
  filtering_candidates_buffered_bpm_distance_retrieve(
      search->filtering_candidates,&search->filtering_candidates_buffered,
      &search->pattern,gpu_buffer_bpm_distance,search->gpu_buffer_bpm_distance_offset);
}
/*
 * BPM-Align Buffered
 */
void approximate_search_bpm_align_buffered_update(
    approximate_search_t* const search) {
  // Update number of internal statistics
	filtering_candidates_buffered_bpm_align_set_num_canonical_candidates(
      search->filtering_candidates,&search->filtering_candidates_buffered,
      &search->pattern);
}
void approximate_search_bpm_align_buffered_copy(
    approximate_search_t* const search,
    gpu_buffer_bpm_align_t* const gpu_buffer_bpm_align) {
  // Add to GPU-Buffer
  filtering_candidates_buffered_bpm_align_add(
      search->filtering_candidates,&search->filtering_candidates_buffered,
      &search->pattern,gpu_buffer_bpm_align,&search->gpu_buffer_bpm_align_offset);
}
void approximate_search_bpm_align_buffered_retrieve(
    approximate_search_t* const search,
    gpu_buffer_bpm_align_t* const gpu_buffer_bpm_align,
    matches_t* const matches) {
  // Retrieve
  filtering_candidates_buffered_bpm_align_retrieve(
      search->filtering_candidates,&search->filtering_candidates_buffered,
      &search->pattern,matches,gpu_buffer_bpm_align,
      search->gpu_buffer_bpm_align_offset);
  // Align
  filtering_candidates_align_candidates(
      search->filtering_candidates,&search->pattern,matches);
  // Update state
  search->processing_state = asearch_processing_state_candidates_verified;
}

