/*
 *  GEM-Mapper v3 (GEM3)
 *  Copyright (c) 2011-2017 by Santiago Marco-Sola  <santiagomsola@gmail.com>
 *
 *  This file is part of GEM-Mapper v3 (GEM3).
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * PROJECT: GEM-Mapper v3 (GEM3)
 * AUTHOR(S): Santiago Marco-Sola <santiagomsola@gmail.com>
 * DESCRIPTION:
 *   Approximate-String-Matching (ASM) module to verify
 *   the filtering-candidates generated by previous stages
 */

#include "approximate_search/approximate_search_verify_candidates.h"
#include "approximate_search/approximate_search_control.h"
#include "filtering/candidates/filtering_candidates_process.h"
#include "filtering/candidates/filtering_candidates_verify.h"
#include "filtering/candidates/filtering_candidates_verify_buffered.h"
#include "filtering/candidates/filtering_candidates_extend.h"
#include "filtering/candidates/filtering_candidates_align.h"

/*
 * Debug
 */
#define DEBUG_REGION_SCHEDULE_PRINT GEM_DEEP_DEBUG

/*
 * Profile
 */
#define PROFILE_LEVEL PMED

/*
 * Benchmark
 */
#ifdef CUDA_BENCHMARK_GENERATE_VERIFY_CANDIDATES
FILE* benchmark_verify_candidates = NULL;
#endif

/*
 * Verify Candidates
 */
void approximate_search_verify_candidates(
    approximate_search_t* const search,
    matches_t* const matches) {
  gem_cond_debug_block(DEBUG_SEARCH_STATE) {
    tab_fprintf(stderr,"[GEM]>ASM::Verify Candidates\n");
    tab_global_inc();
  }
  // Parameters
  pattern_t* const pattern = &search->pattern;
  filtering_candidates_t* const filtering_candidates = search->filtering_candidates;
  // Verify Candidates
  filtering_candidates_verify_candidates(filtering_candidates,pattern);
  filtering_candidates_align_candidates(filtering_candidates,pattern,false,false,matches);
  search->processing_state = asearch_processing_state_candidates_verified;
  gem_cond_debug_block(DEBUG_SEARCH_STATE) { tab_global_dec(); }
}
/*
 * Verify Extend Candidate
 */
uint64_t approximate_search_verify_extend_candidate(
    filtering_candidates_t* const filtering_candidates,
    pattern_t* const candidate_pattern,
    const match_trace_t* const extended_match,
    mapper_stats_t* const mapper_stats,
    paired_matches_t* const paired_matches,
    const sequence_end_t candidate_end) {
  return filtering_candidates_extend_match(filtering_candidates,
      candidate_pattern,extended_match,paired_matches,candidate_end,mapper_stats);
}
/*
 * Verify Candidates Buffered
 */
#ifdef CUDA_BENCHMARK_GENERATE_VERIFY_CANDIDATES
void approximate_search_verify_candidates_buffered_print_benchmark(approximate_search_t* const search);
#endif
void approximate_search_verify_candidates_buffered_copy(
    approximate_search_t* const search,
    gpu_buffer_align_bpm_t* const gpu_buffer_align_bpm) {
  // Add to GPU-Buffer
  filtering_candidates_verify_buffered_add(
      search->filtering_candidates,&search->filtering_candidates_buffered,
      &search->pattern,gpu_buffer_align_bpm,&search->gpu_buffer_align_offset);
  // BENCHMARK
#ifdef CUDA_BENCHMARK_GENERATE_VERIFY_CANDIDATES
  approximate_search_verify_candidates_buffered_print_benchmark(search);
#endif
}
void approximate_search_verify_candidates_buffered_retrieve(
    approximate_search_t* const search,
    gpu_buffer_align_bpm_t* const gpu_buffer_align_bpm,
    matches_t* const matches) {
  // Retrieve
  filtering_candidates_verify_buffered_retrieve(
      search->filtering_candidates,&search->filtering_candidates_buffered,
      &search->pattern,gpu_buffer_align_bpm,search->gpu_buffer_align_offset);
  // Align
  filtering_candidates_align_candidates(search->filtering_candidates,&search->pattern,false,false,matches);
  // Update state
  search->processing_state = asearch_processing_state_candidates_verified;
}
/*
 * Display/Benchmark
 */
#ifdef CUDA_BENCHMARK_GENERATE_VERIFY_CANDIDATES
void approximate_search_verify_candidates_buffered_print_benchmark(approximate_search_t* const search) {
  // Prepare benchmark file
  if (benchmark_verify_candidates==NULL) {
    benchmark_verify_candidates = fopen("gem3.verify.candidates.benchmark","w+");
  }
  // Print all candidates' tiles
  filtering_candidates_verify_buffered_print_benchmark(
      benchmark_verify_candidates,search->filtering_candidates,&search->pattern);
}
#endif

