/*
 * PROJECT: GEMMapper
 * FILE: matches_classify_logit_models.c
 * DATE: 06/06/2012
 * AUTHOR(S): Santiago Marco-Sola <santiagomsola@gmail.com>
 * DESCRIPTION: TODO
 */

#include "matches_classify_logit_models.h"

/*
 * SE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_single_end_default = {
  .unique_logit_coeff = {
    .coeff_intercept                       = -222.2971,
    .coeff_first_map_edit_distance_norm    = 0.0,
    .coeff_first_map_event_distance_norm   = 207.3658,
    .coeff_first_map_swg_score_norm        = 17.8461,
    .coeff_subdominant_edit_distance_norm  = 0.0,
    .coeff_subdominant_event_distance_norm = 0.0,
    .coeff_subdominant_swg_score_norm      = 0.0,
    .coeff_first_stratum_matches           = 0.0,
    .coeff_subdominant_stratum_matches     = 0.0,
    .coeff_mcs                             = 4.7404,
    .coeff_max_region_length_norm          = -0.9996,
    .coeff_subdominant_candidates_end1     = 0.2964,
    .coeff_subdominant_candidates_end2     = 0.0,
    .coeff_first_map_template_size_sigma   = 0.0,
    .coeff_subdominant_template_size_sigma = 0.0,
    .coeff_mapq_end1                       = 0.0,
    .coeff_mapq_end2                       = 0.0,
  },
  .mmaps_logit_coeff = {
    .coeff_intercept                       = -209.7885,
    .coeff_first_map_edit_distance_norm    = 0.0,
    .coeff_first_map_event_distance_norm   = 191.0935,
    .coeff_first_map_swg_score_norm        = 23.3503,
    .coeff_subdominant_edit_distance_norm  = 0.0,
    .coeff_subdominant_event_distance_norm = 2.7940,
    .coeff_subdominant_swg_score_norm      = -6.2635,
    .coeff_first_stratum_matches           = 0.0,
    .coeff_subdominant_stratum_matches     = 0.0,
    .coeff_mcs                             = 3.9139,
    .coeff_max_region_length_norm          = -0.5801,
    .coeff_subdominant_candidates_end1     = 0.1275,
    .coeff_subdominant_candidates_end2     = 0.0,
    .coeff_first_map_template_size_sigma   = 0.0,
    .coeff_subdominant_template_size_sigma = 0.0,
    .coeff_mapq_end1                       = 0.0,
    .coeff_mapq_end2                       = 0.0,
  },
  .ties_logit_coeff = {
    .coeff_intercept                       = -158.99528,
    .coeff_first_map_edit_distance_norm    = 72.02521,
    .coeff_first_map_event_distance_norm   = 229.73507,
    .coeff_first_map_swg_score_norm        = 22.06638,
    .coeff_subdominant_edit_distance_norm  = -62.02260,
    .coeff_subdominant_event_distance_norm = -85.95881,
    .coeff_subdominant_swg_score_norm      = -18.74157,
    .coeff_first_stratum_matches           = 0.0,
    .coeff_subdominant_stratum_matches     = 0.01094,
    .coeff_mcs                             = 1.66582,
    .coeff_max_region_length_norm          = 0.0,
    .coeff_subdominant_candidates_end1     = 0.03268,
    .coeff_subdominant_candidates_end2     = 0.0,
    .coeff_first_map_template_size_sigma   = 0.0,
    .coeff_subdominant_template_size_sigma = 0.0,
    .coeff_mapq_end1                       = 0.0,
    .coeff_mapq_end2                       = 0.0,
  },
};
/*
 * PE-Model DEFAULT
 */
const matches_classify_logit_model_t logit_model_paired_end_default = {
  .unique_logit_coeff = {
    .coeff_intercept                       = -343.3571,
    .coeff_first_map_edit_distance_norm    = 46.6914,
    .coeff_first_map_event_distance_norm   = 301.8511,
    .coeff_first_map_swg_score_norm        = 0.0,
    .coeff_subdominant_edit_distance_norm  = 0.0,
    .coeff_subdominant_event_distance_norm = 0.0,
    .coeff_subdominant_swg_score_norm      = 0.0,
    .coeff_first_stratum_matches           = 0.0,
    .coeff_subdominant_stratum_matches     = 0.0,
    .coeff_mcs                             = 2.3967,
    .coeff_max_region_length_norm          = -0.5880,
    .coeff_subdominant_candidates_end1     = 0.0,
    .coeff_subdominant_candidates_end2     = 0.0,
    .coeff_first_map_template_size_sigma   = -0.5061,
    .coeff_subdominant_template_size_sigma = 0.0,
    .coeff_mapq_end1                       = 0.1308,
    .coeff_mapq_end2                       = 0.0,
  },
  .mmaps_logit_coeff = {
    .coeff_intercept                       = -421.36852,
    .coeff_first_map_edit_distance_norm    = 75.46711,
    .coeff_first_map_event_distance_norm   = 382.99138,
    .coeff_first_map_swg_score_norm        = 18.25120,
    .coeff_subdominant_edit_distance_norm  = -54.84610,
    .coeff_subdominant_event_distance_norm = 0.0,
    .coeff_subdominant_swg_score_norm      = 0.0,
    .coeff_first_stratum_matches           = 0.0,
    .coeff_subdominant_stratum_matches     = 0.0,
    .coeff_mcs                             = 3.13206,
    .coeff_max_region_length_norm          = -0.21534,
    .coeff_subdominant_candidates_end1     = 0.0,
    .coeff_subdominant_candidates_end2     = 0.0,
    .coeff_first_map_template_size_sigma   = 0.0,
    .coeff_subdominant_template_size_sigma = 0.0,
    .coeff_mapq_end1                       = 0.06624,
    .coeff_mapq_end2                       = 0.0,
  },
  .ties_logit_coeff = {
    .coeff_intercept                       = -2.093e+02,
    .coeff_first_map_edit_distance_norm    = 1.465e+02,
    .coeff_first_map_event_distance_norm   = 6.239e+02,
    .coeff_first_map_swg_score_norm        = 4.753e+01,
    .coeff_subdominant_edit_distance_norm  = -1.316e+02,
    .coeff_subdominant_event_distance_norm = -4.275e+02,
    .coeff_subdominant_swg_score_norm      = -5.058e+01,
    .coeff_first_stratum_matches           = 0.0,
    .coeff_subdominant_stratum_matches     = -1.142e-03,
    .coeff_mcs                             = 5.029e-01,
    .coeff_max_region_length_norm          = -1.069e-01,
    .coeff_subdominant_candidates_end1     = 0.0,
    .coeff_subdominant_candidates_end2     = 0.0,
    .coeff_first_map_template_size_sigma   = -8.142e-01,
    .coeff_subdominant_template_size_sigma = 7.452e-01,
    .coeff_mapq_end1                       = 1.818e-02,
    .coeff_mapq_end2                       = 0.0,
  },
};



//matches_classify_logit_model_t logit_model_se_default = {
//  .unique_logit_coeff = {
//    .coeff_intercept                       = ,
//    .coeff_first_map_edit_distance_norm    = ,
//    .coeff_first_map_event_distance_norm   = ,
//    .coeff_first_map_swg_score_norm        = ,
//    .coeff_subdominant_edit_distance_norm  = ,
//    .coeff_subdominant_event_distance_norm = ,
//    .coeff_subdominant_swg_score_norm      = ,
//    .coeff_first_stratum_matches           = ,
//    .coeff_subdominant_stratum_matches     = ,
//    .coeff_mcs                             = ,
//    .coeff_max_region_length_norm          = ,
//    .coeff_subdominant_candidates_end1     = ,
//    .coeff_subdominant_candidates_end2     = ,
//    .coeff_first_map_template_size_sigma   = ,
//    .coeff_subdominant_template_size_sigma = ,
//    .coeff_mapq_end1                       = ,
//    .coeff_mapq_end2                       = ,
//  },
//  .mmaps_logit_coeff = {
//    .coeff_intercept                       = ,
//    .coeff_first_map_edit_distance_norm    = ,
//    .coeff_first_map_event_distance_norm   = ,
//    .coeff_first_map_swg_score_norm        = ,
//    .coeff_subdominant_edit_distance_norm  = ,
//    .coeff_subdominant_event_distance_norm = ,
//    .coeff_subdominant_swg_score_norm      = ,
//    .coeff_first_stratum_matches           = ,
//    .coeff_subdominant_stratum_matches     = ,
//    .coeff_mcs                             = ,
//    .coeff_max_region_length_norm          = ,
//    .coeff_subdominant_candidates_end1     = ,
//    .coeff_subdominant_candidates_end2     = ,
//    .coeff_first_map_template_size_sigma   = ,
//    .coeff_subdominant_template_size_sigma = ,
//    .coeff_mapq_end1                       = ,
//    .coeff_mapq_end2                       = ,
//  },
//  .ties_logit_coeff = {
//    .coeff_intercept                       = ,
//    .coeff_first_map_edit_distance_norm    = ,
//    .coeff_first_map_event_distance_norm   = ,
//    .coeff_first_map_swg_score_norm        = ,
//    .coeff_subdominant_edit_distance_norm  = ,
//    .coeff_subdominant_event_distance_norm = ,
//    .coeff_subdominant_swg_score_norm      = ,
//    .coeff_first_stratum_matches           = ,
//    .coeff_subdominant_stratum_matches     = ,
//    .coeff_mcs                             = ,
//    .coeff_max_region_length_norm          = ,
//    .coeff_subdominant_candidates_end1     = ,
//    .coeff_subdominant_candidates_end2     = ,
//    .coeff_first_map_template_size_sigma   = ,
//    .coeff_subdominant_template_size_sigma = ,
//    .coeff_mapq_end1                       = ,
//    .coeff_mapq_end2                       = ,
//  },
//}
